### ISSUE TITLE
[Feature] MCS: Traffic manager resource identifiers need to be readable (not UUIDs)

### ISSUE THREAD

**Issue by sjwaight** [Azure/fleet-networking#236]
When interacting with TrafficManagerBackend or TrafficManagerProfile CRs any references to Traffic Manager instances should use human readable Traffic Manager resource names and not render resource IDs (UUIDs).

**Comment by zhiying-lin** [comment]
The reason of using uuid is to solve the name conflict issue, especially when we introduce BYO resource group/profile. The atm resources are supposed to be managed by our controllers, instead of human. For easier debugging/troubleshooting, it should be addressed in #237 to use the azure resource id returned in the status.
